version: 2.1

jobs:
  build_macos:
    macos:
      xcode: 11.7
    steps:
      - checkout
      - run:
          name: Install Python
          command: |
            brew install python@3.9
            python --version
      - run:
          name: build node
          command: |
            pip install -r requirements.txt
            conan create . _/_ -sbuild_type=Release -oshared=True