name: Build nodejs library

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      CONAN_CMAKE_GENERATOR: ninja
      CONAN_REVISIONS_ENABLED: 1
    strategy:
      matrix:
        os: [ macos-11, macos-12, macos-13 ]
    steps:
      - name: Check out Git repositorygit
        uses: actions/checkout@v1
      - name: Install Dependency
        run: pip3 install -r requirements.txt
      - name: Setup Conan Remote
        run: |
          conan remote add conan https://conan.bzdrs.cn/artifactory/api/conan/conan
          conan user -p ${{ secrets.CONAN_SECRET }} -r conan admin
      - name: Build
        run: conan create . _/_ --build=missing -sbuild_type=Release -oshared=True
      - name: Upload
        run: conan upload node/18.16.0 --all -r conan --retry 3 --retry-wait 10